src/Entity/Game.php
<?php

namespace App\Entity;

use ApiPlatform\Core\Annotation\ApiResource;
use App\Repository\GameRepository;
use Cocur\Slugify\Slugify;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;

#[ORM\Entity(repositoryClass: GameRepository::class)]
#[ApiResource]
class Game
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column(type: 'integer')]
    private $id;

    #[ORM\Column(type: 'string', length: 255)]
    private $name;

    #[ORM\Column(type: 'string', length: 255)]
    private $slug;

    #[ORM\ManyToMany(targetEntity: GameGenre::class)]
    private $type;

    #[ORM\Column(type: 'float')]
    private $price;

    #[ORM\OneToMany(mappedBy: 'game', targetEntity: Media::class)]
    private $pictures;

    #[ORM\Column(type: 'array')]
    private $platforms = [];

    #[ORM\Column(type: 'float', nullable: true)]
    private $promotion;

    #[ORM\Column(type: 'datetime')]
    private $dateAdded;

    #[ORM\Column(type: 'datetime', nullable: true)]
    private $dateRelease;

    #[ORM\Column(type: 'text')]
    private $description;

    #[ORM\Column(type: 'string', length: 255, nullable: true)]
    private $youtubeLink;

    #[ORM\OneToMany(mappedBy: 'game', targetEntity: Review::class)]
    private $reviews;

    #[ORM\Column(type: 'float', nullable: true)]
    private $averageReview;

    #[ORM\Column(type: 'integer', nullable: true)]
    private $reviewCount;

    public function __construct(string $name,
                                float  $price = 0,
                                array  $platforms = [])
    {
        $this->setName($name);
        $this->price = $price;
        $this->platforms = $platforms;
        $this->dateAdded = new \DateTime();
        $this->promotion = null;
        $this->description = '';

        $this->type = new ArrayCollection();
        $this->pictures = new ArrayCollection();
        $this->reviews = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getName(): ?string
    {
        return $this->name;
    }

    public function setName(string $name): self
    {
        $this->name = $name;

        $slugify = new Slugify();
        $this->slug = $slugify->slugify($name);
        return $this;
    }

    public function getSlug(): ?string
    {
        return $this->slug;
    }

    public function setSlug(string $slug): self
    {
        $this->slug = $slug;

        return $this;
    }

    /**
     * @return Collection<int, GameGenre>
     */
    public function getType(): Collection
    {
        return $this->type;
    }

    public function addType(GameGenre $type): self
    {
        if (!$this->type->contains($type)) {
            $this->type[] = $type;
        }

        return $this;
    }

    public function removeType(GameGenre $type): self
    {
        $this->type->removeElement($type);

        return $this;
    }

    public function getPrice(): ?float
    {
        return $this->price;
    }

    public function getPriceWithPromotion(): ?float
    {
        if ($this->promotion <= 0) {
            return $this->price;
        }
        return round($this->price * ((100 - $this->promotion) / 100), 2);
    }

    public function setPrice(float $price): self
    {
        $this->price = $price;

        return $this;
    }

    /**
     * @return Collection<int, Media>
     */
    public function getPictures(): Collection
    {
        return $this->pictures;
    }

    public function addPicture(Media $picture): self
    {
        if (!$this->pictures->contains($picture)) {
            $this->pictures[] = $picture;
            $picture->setGame($this);
        }

        return $this;
    }

    public function removePicture(Media $picture): self
    {
        if ($this->pictures->removeElement($picture)) {
            // set the owning side to null (unless already changed)
            if ($picture->getGame() === $this) {
                $picture->setGame(null);
            }
        }

        return $this;
    }

    public function getPlatforms(): ?array
    {
        return $this->platforms;
    }

    public function setPlatforms(array $platforms): self
    {
        $this->platforms = $platforms;

        return $this;
    }

    public function getPromotion(): ?float
    {
        return $this->promotion;
    }

    public function setPromotion(?float $promotion): self
    {
        $this->promotion = $promotion;

        return $this;
    }

    public function getDateAdded(): ?\DateTimeInterface
    {
        return $this->dateAdded;
    }

    public function setDateAdded(\DateTimeInterface $dateAdded): self
    {
        $this->dateAdded = $dateAdded;

        return $this;
    }

    public function getDateRelease(): ?\DateTimeInterface
    {
        return $this->dateRelease;
    }

    public function setDateRelease(?\DateTimeInterface $dateRelease): self
    {
        $this->dateRelease = $dateRelease;

        return $this;
    }

    public function getDescription(): ?string
    {
        return $this->description;
    }

    public function setDescription(string $description): self
    {
        $this->description = $description;

        return $this;
    }

    public function getYoutubeLink(): ?string
    {
        return $this->youtubeLink;
    }

    public function getYoutubeID(): ?string
    {
        if ($this->youtubeLink === null) {
            return null;
        }
        $url = parse_url($this->youtubeLink);
        if ($url === false) {
            return null;
        }
        $query = $url['query'];
        $query = explode('&', $query);
        foreach ($query as $q) {
            $q = explode('=', $q);
            if ($q[0] === 'v') {
                return $q[1];
            }
        }
        return $this->youtubeLink;
    }

    public function setYoutubeLink(?string $youtubeLink): self
    {
        $this->youtubeLink = $youtubeLink;

        return $this;
    }

    /**
     * @return Collection<int, Review>
     */
    public function getReviews(): Collection
    {
        return $this->reviews;
    }

    public function addReview(Review $review): self
    {
        if (!$this->reviews->contains($review)) {
            $this->reviews[] = $review;
            $review->setGame($this);
        }

        return $this;
    }

    public function removeReview(Review $review): self
    {
        if ($this->reviews->removeElement($review)) {
            // set the owning side to null (unless already changed)
            if ($review->getGame() === $this) {
                $review->setGame(null);
            }
        }

        return $this;
    }

    public function getAverageReview(): ?float
    {
        return $this->averageReview;
    }

    public function setAverageReview(?float $averageReview): self
    {
        $this->averageReview = $averageReview;

        return $this;
    }

    public function getReviewCount(): ?int
    {
        return $this->reviewCount;
    }

    public function setReviewCount(?int $reviewCount): self
    {
        $this->reviewCount = $reviewCount;

        return $this;
    }
}

templates/base.html.twig
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{% block title %}Welcome!{% endblock %}</title>
    <link rel="icon"
          href="data:image/svg+xml,<svg xmlns=%22http://www.w3.org/2000/svg%22 viewBox=%220 0 128 128%22><text y=%221.2em%22 font-size=%2296%22>⚫️</text></svg>">
    {% block stylesheets %}
        <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css"
              rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC"
              crossorigin="anonymous">
    {% endblock %}

    {% block javascripts %}

    {% endblock %}
</head>
<body>
{% include '/inc/header.html.twig' %}
<div class="container-fluid">
    {% block body %}{% endblock %}
</div>
<footer>
    {% include '/inc/footer.html.twig' %}
</footer>
</body>
</html>

templates/base_steam.html.twig
<!DOCTYPE html>
<html lang="fr">
<head>
    <meta charset="UTF-8">
    <meta content="width=device-width, initial-scale=1" name="viewport">
    <title>{% block title %}Steam{% endblock %}</title>
    {% block stylesheets %}
        <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/notyf@3/notyf.min.css">
        <link href="{{ asset('assets/dist/main.css') }}" rel="stylesheet">
    {% endblock %}
</head>
<body>
{% include 'includes/steam/nav.html.twig' %}
{% block body %}{% endblock %}
{% block javascripts %}
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js"
            integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo"
            crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.14.7/dist/umd/popper.min.js"
            integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1"
            crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.3.1/dist/js/bootstrap.min.js"
            integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM"
            crossorigin="anonymous"></script>

    <script src="https://cdn.jsdelivr.net/npm/notyf@3/notyf.min.js"></script>

    <script src="{{ asset('assets/js/search.js') }}"></script>
    <script src="{{ asset('assets/js/cart.js') }}"></script>
{% endblock %}
</body>
<head>

templates/index.html.twig
{% extends 'base.html.twig' %}

{% block stylesheets %}
    {{ parent() }}
    <link rel="stylesheet" href="/assets/dist/main.css">
{% endblock %}

{% block body %}
    <div class="p-4 p-md-5 mb-4 text-white rounded bg-dark">
        <div class="col-md-6 px-0">
            <h1 class="display-4 fst-italic">Hello {{ user.name }} !</h1>
            <p class="lead my-3">{{ troll }}</p>
            <p class="lead mb-0"><a href="#" class="text-white fw-bold">Continue reading...</a></p>
        </div>
    </div>
    <!-- article -->
    <div class="row mb-2">
        {% for article in articles %}
            <div id="{{ article.guid }}" class="col-md-6">
                <div class="row g-0 border rounded overflow-hidden flex-md-row mb-4 shadow-sm h-md-250 position-relative">
                    <div class="col p-4 d-flex flex-column position-static">
                        <strong class="d-inline-block mb-2 text-success">{{ article.author }}</strong>
                        <h3 class="mb-0">{{ article.title }}</h3>
                        <div class="mb-1 text-muted">{{ article.pubDate|date("m/d/Y H:i:s") }}</div>
                        <p class="mb-auto">
                            {{ article.description|raw }}
                        </p>
                        <a href="#" class="stretched-link">Continue reading</a>
                    </div>
                    <div class="col-auto d-none d-lg-block">
                        <img src="{{ article.thumbnail }}" alt="">
                    </div>
                </div>
            </div>
        {% endfor %}
    </div>
    <!-- /article -->
{% endblock %}

templates/page_achat.html.twig
{% extends 'base_steam.html.twig' %}

{% block body %}
    <main>
        <div class="container">
            {% include "includes/steam/top-menu.html.twig" %}
        </div>

        <div class="container-custom">
            <section class="container mt-5">
                <div class="row">
                    <div class="col-12 col-md-8 position-relative mb-3">
                        <div class="hero-header-img-small position-relative">
                            {% if game.pictures.first != false %}
                                <img src="{{ game.pictures.first.url }}"
                                     alt="{{ game.name }}" class="">
                            {% else %}
                                <img src="/assets/images/satisfactory.png" alt="satisfactory">
                            {% endif %}
                        </div>
                    </div>

                    <div class="col-12 col-md-4">
                        {% for img in game.pictures %}
                            {% if not loop.first and loop.index <= 3 %}
                                <div class="mb-2 hero-header-img-small">
                                    <img src="{{ img.url }}" style="border-radius: 20px;" alt="{{ game.name }}"
                                         class="w-100">
                                </div>
                            {% endif %}
                        {% endfor %}
                    </div>
                </div>
            </section>
        </div>

        <div class="container-custom">
            <section class="container py-3">
                <div class="row row-cols-2 row-cols-md-3 row-cols-lg-5">
                    {% for img in game.pictures %}
                        <div class="col">
                            <div class="card card-game">
                                <div class="card-img-top">
                                    <img src="{{ img.url }}"
                                         class="w-100" alt="{{ game.name }}">
                                </div>
                            </div>
                        </div>
                    {% endfor %}
                </div>

                <div class="slider mt-3">
                    <div class="current"></div>
                </div>
            </section>
        </div>

        <div class="container-custom">
            <section class="container py-3">
                <h1 class="text-uppercase">{{ game.name }}</h1>
                <p>{{ game.description }}</p>

                {% if game.youtubeLink is not null %}
                    <section class="youtube-video d-flex justify-content-center align-items-center">
                        <div class="video-wrapper p-2">
                            <iframe width="560" height="315"
                                    src="https://www.youtube-nocookie.com/embed/{{ game.youtubeID }}?controls=0"
                                    title="YouTube video player"
                                    frameborder="0"
                                    allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture"
                                    allowfullscreen></iframe>
                        </div>
                    </section>
                {% endif %}

                <div class="row  align-items-center justify-content-between">
                    <div class="col-12 col-md-3 mt-4">
                        <div class="avis-text me-4">
                            {% if game.reviewCount is null or game.reviewCount <= 0 %}
                                <p class="m-0 text-muted">No Review</p>
                            {% else %}
                                <p class="m-0">Review <span
                                            style="white-space:nowrap">{{ game.reviewCount|number_format(0, ',', ' ') }}</span>
                                </p>
                            {% endif %}
                            <div class="avis d-flex align-items-center">
                                {% import "macros/pricing.macro.twig" as pricingMacro %}
                                {{ pricingMacro.review_stars(game.averageReview) }}
                            </div>
                        </div>
                    </div>
                    <div class="col-12 col-md-9 mt-4">
                        <div class="d-flex justify-content-end">
                            <div class="px-2">
                                {% import "macros/pricing.macro.twig" as pricingMacro %}
                                {{ pricingMacro.pricing(game.price, game.promotion) }}
                            </div>

                            <a href="#"
                               data-id="{{ game.id }}"
                               class="btn btn-warning btn-lg me-2 add-to-cart">Ajouter au
                                panier 🛒 !</a>
                            <a href="#game-suggestion" class="btn btn-primary btn-lg">Jeux similaires</a>
                        </div>
                    </div>
                </div>

                <div class="row py-5 align-items-center">
                    <div class="col-12 col-md-5 mb-4">
                        <div class="bg-primary rounded">
                            <div class="caracteristique-line">
                                <img src="/assets/images/amis.png">
                                Solo, Multijoueur
                            </div>
                            <div class="caracteristique-line">
                                <img src="/assets/images/amis.png">
                                <ul>
                                    {% for genre in game.type %}
                                        <li>{{ genre.name }}</li>
                                    {% endfor %}
                                </ul>
                            </div>

                            <div class="d-flex align-items-center justify-content-between caracteristique-line flex-wrap">
                                {% for platform in game.platforms %}
                                    <div
                                            class="badge rounded-pill bg-dark m-1">{{ platform }}</div>
                                {% endfor %}
                            </div>
                        </div>
                    </div>
                    <div class="col-12 col-md-7 mb-4">

                        {% if game.pictures.last != false %}
                            <img src="{{ game.pictures.last.url }}"
                                 style="border-radius: 20px;"
                                 alt="{{ game.name }}" class="w-100">
                        {% else %}
                            <img src="/assets/images/satisfactory.png" class="w-100" alt="satisfactory">
                        {% endif %}
                    </div>
                </div>

                <section id="game-suggestion" class="game-suggestion">
                    <div class="d-block h3 pt-4 mb-4">Jeux similaires</div>
                    {% if similarGames|length <= 0 %}
                        <div class="w-100 d-flex justify-content-center align-items-center">
                            <div class=" text-muted p-3">aucun jeu 😅</div>
                        </div>
                    {% else %}
                        <div class="w-100">
                            <div class="row row-cols-1 row-cols-sm-2 row-cols-lg-3 row-cols-xl-4">
                                {% for sgame in similarGames %}
                                    {% include 'includes/steam/game-card.html.twig' with {'game': sgame} %}
                                {% endfor %}
                            </div>
                        </div>
                    {% endif %}
                </section>


            </section>
        </div>
    </main>
{% endblock %}

templates/page_form_steam.html.twig
{% extends 'base_steam.html.twig' %}

{% block body %}
    <main>
        <div class="container">
            {% include "includes/steam/top-menu.html.twig" %}
        </div>

        <div class="container-custom">
            <section class="container-lg mt-5">
                <div class="max-800 m-auto text-center">
                    <h1>Postez votre produit sur Steam</h1>
                    <p>
                        Nous nous assurons que notre platforme soit la plus “propre” possible, nous vérifions donc
                        chaque produit posté sur Steam. Veuillez ne pas créer de produits à l’encontre de notre
                        règlement.
                    </p>
                </div>
            </section>
        </div>

        <div class="container-custom">
            <section class="container py-5 section-form">
                <div class="row row-cols-1 row-cols-lg-3">
                    <div class="col mb-5">
                        <h2 class="h3">Informations Principales</h2>
                        {{ form(myForm) }}
                    </div>
                </div>
            </section>
        </div>
    </main>
{% endblock %}